/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tarekboutefara.contactsbdd.gui;

import com.tarekboutefara.contactsbdd.controller.MainController;
import com.tarekboutefara.contactsbdd.model.Contacts;
import com.tarekboutefara.contactsbdd.model.Personne;
import com.tarekboutefara.contactsbdd.model.PersonneBuilder;

/**
 *
 * @author Tarek Boutefara <t_boutefara@esi.dz>
 */
public class Contact extends javax.swing.JFrame {
    
    int courrant;
    boolean nouveau;

    /**
     * Creates new form Contact
     */
    public Contact() {
        initComponents();
        
        
        if(Contacts.listeContacts().isEmpty()){
            saisieNouveau();
        }else{
            courrant = 0;
            afficherPersonne();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCode = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblPrenom = new javax.swing.JLabel();
        lblAdresse = new javax.swing.JLabel();
        lblNTel = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        sclAdresse = new javax.swing.JScrollPane();
        txtAdresse = new javax.swing.JTextArea();
        txtNTel = new javax.swing.JTextField();
        btnPremier = new javax.swing.JButton();
        btnPrecedent = new javax.swing.JButton();
        btnNouveau = new javax.swing.JButton();
        btnSauver = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        btnDernier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion des Contacts");

        lblCode.setText("Code");

        lblNom.setText("Nom");

        lblPrenom.setText("Prénom");

        lblAdresse.setText("Adresse");

        lblNTel.setText("Numéro de Téléphone");

        txtAdresse.setColumns(20);
        txtAdresse.setRows(5);
        sclAdresse.setViewportView(txtAdresse);

        btnPremier.setText("Premier");
        btnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierActionPerformed(evt);
            }
        });

        btnPrecedent.setText("Pérécdent");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });

        btnNouveau.setText("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        btnSauver.setText("Sauvegarder");
        btnSauver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauverActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnSuivant.setText("Suivant");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });

        btnDernier.setText("Dernier");
        btnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNTel)
                            .addComponent(lblAdresse)
                            .addComponent(lblPrenom)
                            .addComponent(lblNom)
                            .addComponent(lblCode))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCode)
                            .addComponent(txtNom)
                            .addComponent(txtPrenom)
                            .addComponent(sclAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(txtNTel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnPremier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPrecedent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNouveau)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSauver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSupprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSuivant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDernier)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrenom)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdresse)
                    .addComponent(sclAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNTel)
                    .addComponent(txtNTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPremier)
                    .addComponent(btnPrecedent)
                    .addComponent(btnNouveau)
                    .addComponent(btnSauver)
                    .addComponent(btnSupprimer)
                    .addComponent(btnSuivant)
                    .addComponent(btnDernier))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierActionPerformed
        courrant = 0;
        afficherPersonne();
    }//GEN-LAST:event_btnPremierActionPerformed

    private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
        courrant--;
        if(courrant < 0)
            courrant = Contacts.listeContacts().size() - 1;
        
        afficherPersonne();
    }//GEN-LAST:event_btnPrecedentActionPerformed

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
        txtCode.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtAdresse.setText("");
        txtNTel.setText("");
        
        saisieNouveau();
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnSauverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauverActionPerformed
        
        if(nouveau){
            Personne p = creerNouveau();
            MainController.sauver(p);
            finNouveau();
        }else{
            mettreAJour();
            MainController.mettreAJour(courrant);
        }
        
    }//GEN-LAST:event_btnSauverActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        MainController.supprimer(courrant);
        courrant--;
        if(courrant < 0)
            courrant = Contacts.listeContacts().size() - 1;
        
        if(courrant > -1)
            afficherPersonne();
        else
            saisieNouveau();
        
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
        courrant++;
        if(courrant == Contacts.listeContacts().size()){
            courrant = 0;
        }
        
        afficherPersonne();
    }//GEN-LAST:event_btnSuivantActionPerformed

    private void btnDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierActionPerformed
        courrant = Contacts.listeContacts().size() - 1;
        
        if(courrant > -1)
            afficherPersonne();
        else
            saisieNouveau();
    }//GEN-LAST:event_btnDernierActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDernier;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnPremier;
    private javax.swing.JButton btnSauver;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel lblAdresse;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblNTel;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblPrenom;
    private javax.swing.JScrollPane sclAdresse;
    private javax.swing.JTextArea txtAdresse;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNTel;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables

    private void afficherPersonne() {
        Personne p = Contacts.listeContacts().get(courrant);
        txtCode.setText("" + p.getCode());
        txtNom.setText(p.getNom());
        txtPrenom.setText(p.getPrenom());
        txtAdresse.setText(p.getAdresse());
        txtNTel.setText(p.getnTel());
    }

    private void saisieNouveau() {
        btnDernier.setEnabled(false);
        btnSuivant.setEnabled(false);
        btnSupprimer.setEnabled(false);
        btnNouveau.setEnabled(false);
        btnPrecedent.setEnabled(false);
        btnPremier.setEnabled(false);
        
        nouveau = true;
        courrant = -1;
    }

    private Personne creerNouveau() {
        return PersonneBuilder.creerNouveau()
                .avecCode(Integer.parseInt(txtCode.getText()))
                .avecNom(txtNom.getText())
                .avecPrenom(txtPrenom.getText())
                .avecAdresse(txtAdresse.getText())
                .avecNTel(txtNTel.getText())
                .creerReduit();
    }

    private void finNouveau() {
        btnDernier.setEnabled(true);
        btnSuivant.setEnabled(true);
        btnSupprimer.setEnabled(true);
        btnNouveau.setEnabled(true);
        btnPrecedent.setEnabled(true);
        btnPremier.setEnabled(true);
        
        nouveau = false;
        courrant = Contacts.listeContacts().size() - 1;
        
        afficherPersonne();
    }

    private void mettreAJour() {
        Contacts.listeContacts().get(courrant).setNom(txtNom.getText());
        Contacts.listeContacts().get(courrant).setPrenom(txtPrenom.getText());
        Contacts.listeContacts().get(courrant).setAdresse(txtAdresse.getText());
        Contacts.listeContacts().get(courrant).setnTel(txtNTel.getText());
    }
}
